version: '3.3'

services:
  db:
    image: mariadb:10.0.38
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local

  web:
    build:
        context: ./images/web
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html
      - ./config/php:/usr/local/etc/php
      - ./config/ssl:/etc/ssl
      - ./logs/apache2:/var/log/apache2
      - ./config/vhosts:/etc/apache2/sites-enabled 
    ports:
      - "80:80"
      - "443:443"
    links: 
      - db
    restart: always
