version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: images/db/Dockerfile
    volumes:
      # data
      - ./data/mysql/:/var/lib/mysql/

      # logs
      - ./logs/mysql/:/var/log/mysql/

      # socks
      - ./data/run/mysqld/:/var/run/mysqld/
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"

  php_72:
    build:
      context: .
      dockerfile: images/php/Dockerfile
    env_file:
      - .env
    volumes:
      # data
      - ./www/:/var/www/html/

      # config
      - ./config/php/php.ini:/usr/local/etc/php/php.ini

      # logs
      - ./logs/apache2/:/var/log/apache2/
      - ./logs/xdebug/:/var/log/xdebug/
      - ./logs/php/:/var/log/php/
    depends_on:
      - db
    links:
      - db
    restart: always

  php_56:
    build:
      context: .
      dockerfile: images/php/Dockerfile
      args:
        - PHP_VERSION=5.6
    env_file:
      - .env
    volumes:
      # data
      - ./www/:/var/www/html/

      # config
      - ./config/php/php.ini:/usr/local/etc/php/php.ini

      # logs
      - ./logs/apache2/:/var/log/apache2/
      - ./logs/xdebug/:/var/log/xdebug/
      - ./logs/php/:/var/log/php/
    depends_on:
      - db
    links:
      - db
    restart: always

  apache2:
    image: httpd:2.4
    volumes:
      # data
      - ./www/:/var/www/html/

      # config
      - ./config/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./config/apache2/vhosts/:/usr/local/apache2/conf/sites-enabled/
      - ./config/ssl/:/usr/local/apache2/conf/ssl/

      # logs
      - ./logs/apache2/:/var/www/logs/
    ports:
      - "80:80"
      - "443:443"
    links:
      - php_72
      - php_56
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - db
