version: '3.3'

services:
  db:
    image: mariadb:10.0.38
    volumes:
      # data
      - ./data/mysql/:/var/lib/mysql/

      # config
      # - ./config/mysql/:/etc/mysql/conf.d/

      # logs
      - ./logs/mysql/:/var/log/mysql/
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    # command: bash -c "chmod 0440 -R /etc/mysql/conf.d/ && docker-entrypoint.sh mysqld"

  web:
    build:
      context: ./images/web/
    depends_on:
      - db
    volumes:
      # Data
      - ./www/:/var/www/html/                            # Alle Webseiten

      # config
      - ./config/php/php.ini:/usr/local/etc/php/php.ini  # Kopiere die PHP-Einstellungen
      - ./config/ssl/:/etc/ssl/                          # Kopiere die eigenen SSL-Schlüssel
      - ./config/vhosts/:/etc/apache2/sites-enabled/     # Apche-Einstellungen für alle VHost-Einträge

      # logs
      - ./logs/apache2/:/var/log/apache2/                # Apache-Logs
      - ./logs/xdebug/:/var/log/xdebug/                  # XDebug-Logs
      - ./logs/php/:/var/log/php/                        # PHP-Logs
    ports:
      - "80:80"
      - "443:443"
    links: 
      - db
    restart: always
