<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_59ede9afe788e',
    'title' => 'Downloads',
    'fields' => array(
        array(
            'key' => 'field_5a96a6a7fc30f',
            'label' => 'Art',
            'name' => 'download_type',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'E-Book' => 'E-Book',
                'Infografik' => 'Infografik',
                'Whitepaper' => 'Whitepaper',
            ),
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5a96a73dfc311',
            'label' => 'Bessere Position',
            'name' => 'download_position',
            'type' => 'true_false',
            'instructions' => 'Soll diese Stellenanzeige eine bessere Position bei den Suchergebnissen bekommen ?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5a96a88dfc319',
            'label' => 'Formular-Titel',
            'name' => 'download_form_title',
            'type' => 'text',
            'instructions' => 'Standardwort: "Herunterladen"',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Herunterladen',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5a96a8a1fc31a',
            'label' => 'Formular',
            'name' => 'download_form_pardot',
            'type' => 'pardot',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'allow_null' => 0,
            'ui' => 1,
            'ajax' => 0,
            'multiple' => 0,
            'choices' => array(
            ),
            'placeholder' => '',
            'disabled' => 0,
            'readonly' => 0,
            'default_value' => array(
            ),
        ),
        array(
            'key' => 'field_5e15f6a60053e',
            'label' => 'Download-Typ',
            'name' => 'download_file_typ',
            'type' => 'true_false',
            'instructions' => 'Soll eine Datei oder eine URL angegeben werden',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => 'Url',
            'ui_off_text' => 'Datei',
        ),
        array(
            'key' => 'field_5df8b4be3284a',
            'label' => 'Download-File',
            'name' => 'download_file',
            'type' => 'file',
            'instructions' => 'In der Autoresponder-Mail wird auf diese Datei verlinkt.',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5e15f6a60053e',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5e15f7500053f',
            'label' => 'Download-URL',
            'name' => 'download_file_url',
            'type' => 'url',
            'instructions' => 'In der Autoresponder-Mail wird diese URL verlinkt.',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5e15f6a60053e',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5a96a864fc318',
            'label' => 'Bild',
            'name' => 'download_image',
            'type' => 'image',
            'instructions' => 'Das Bild wird in der Größe ausgespielt, wie hier hochgeladen.
Das Bild sollte eine maximale Breite von 230px haben.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5a96a3dbfc30e',
            'label' => 'Kurzbeschreibung',
            'name' => 'download_kurzbeschreibung',
            'type' => 'textarea',
            'instructions' => 'Wird auf Übersichtsseiten ausgespielt. Bsp.: https://mindsquare.de/downloads',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => 170,
            'rows' => 3,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_5a96a81dfc315',
            'label' => 'Einleitungstext',
            'name' => 'download_text',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'field_5a96a837fc316',
            'label' => 'Bulletpoints',
            'name' => 'download_bulletpoints',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_5a96a852fc317',
                    'label' => 'Text',
                    'name' => 'bullet_text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5ab2078d67408',
            'label' => 'Beschreibung',
            'name' => 'download_content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'field_5b582cc781f60',
            'label' => 'Partnerbild',
            'name' => 'download_partner_image',
            'type' => 'image',
            'instructions' => 'Wird über dem Formular-Titel ausgespielt.
Die maximalen Maße sind 150px × 50px (B × H).',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5d318f9c91dd2',
            'label' => '',
            'name' => '',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5d14bf43b8cb2',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'downloads',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
));

endif;
