<?php 
if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(array (
		'key' => 'group_5859212e79efe',
		'title' => 'Header IT-Karriere',
		'fields' => array (
			array (
				'key' => 'field_585921399b54a',
				'label' => 'Fünf Gründe Text',
				'name' => 'funf_grunde_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_585921679b54c',
				'label' => 'Fünf Gründe',
				'name' => 'funf_grunde',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5859219a9b54d',
				'min' => '',
				'max' => 5,
				'layout' => 'table',
				'button_label' => 'Eintrag hinzufügen',
				'sub_fields' => array (
					array (
						'key' => 'field_5859219a9b54d',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'field_585aa568b289d',
				'label' => 'Buttontext im Header',
				'name' => 'buttontext_im_header',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Jetzt <strong>bewerben</strong>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_585aa581b289e',
				'label' => 'Buttonlink im Header',
				'name' => 'buttonlink_im_header',
				'type' => 'url',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'https://mindsquare.de/karriere/stellenangebote/',
				'placeholder' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-it-career.php',
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-page-builder-it-career.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'the_content',
		),
		'active' => 1,
		'description' => '',
	));
endif;
?>