<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b151f43e9118',
		'title' => 'Webinare - Einstellungen',
		'fields' => array(
			array(
				'key' => 'field_5b151f4c551af',
				'label' => 'Termine',
				'name' => 'webinare_option_appointments',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5b151f97551b0',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Termin hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_5b151f97551b0',
						'label' => 'Wochentag',
						'name' => 'webinar_weekday',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '56',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							0 => 'Montag',
							1 => 'Dienstag',
							2 => 'Mittwoch',
							3 => 'Donnerstag',
							4 => 'Freitag',
							5 => 'Samstag',
							6 => 'Sonntag',
						),
						'default_value' => array(
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b151fbc551b1',
						'label' => 'Uhrzeit',
						'name' => 'webinar_time_h',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'acf-timepick',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => 23,
						'step' => 1,
					),
					array(
						'key' => 'field_5b151ff5551b2',
						'label' => '',
						'name' => 'webinar_time_i',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'acf-timepick',
							'id' => '',
						),
						'default_value' => '00',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'Uhr',
						'min' => 0,
						'max' => 59,
						'step' => 1,
					),
				),
			),
			array(
				'key' => 'field_5c51c249dddd7',
				'label' => 'Webinar Partner Bild',
				'name' => 'webinare_option_partner_logo',
				'type' => 'image',
				'instructions' => 'Das Bild sollte eine maximale Größe von 150px x 50px haben',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-msq-webinare',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	endif;