<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_583edd4659541',
		'title' => 'Stellenanzeigen - Einstellungen',
		'fields' => array(
			array(
				'key' => 'field_59509f29790de',
				'label' => 'Allgemein',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_583ede0178d86',
				'label' => 'Titel "Lernen auf der Überholspur"',
				'name' => 'titel_lernen_auf_der_uberholspur',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Lernen auf der Überholspur',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_583ede1c78d87',
				'label' => 'Text "Lernen auf der Überholspur"',
				'name' => 'text_lernen_auf_der_uberholspur',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Kontinuierliches Lernen und die Weiterentwicklung unserer Mitarbeiter sind tief in unseren Unternehmenswerten verankert. So untersützen wir durch unser einzigartiges Aus- und Weiterbildungskonzept jeden Mitarbeiter dabei, über sich hinauszuwachsen, fachlich und persönlich. So entwickeln wir auch dich in 2 Jahren vom Absolventen zum IT Manager.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_5950a1555d30a',
				'label' => 'Video Fallback "Wir bieten dir"',
				'name' => 'video_fallback',
				'type' => 'oembed',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'width' => '',
				'height' => '',
			),
			array(
				'key' => 'field_5950a1c25d30b',
				'label' => 'Bild Fallback "Das bringst du mit"',
				'name' => 'bild_fallback',
				'type' => 'image',
				'instructions' => 'Das Bild sollte eine minimale Größe von 300x178px oder 300x210px haben',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_583eddd978d85',
				'label' => 'mindsquare Vorteile Link',
				'name' => 'mindsquare_vorteile_link',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_584aab2ecd96d',
				'label' => 'Alle Stellenangebote Link',
				'name' => 'alle_stellenangebote_link',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_58afd651fa4ff',
				'label' => 'Bewerben Button ändern?',
				'name' => 'bewerben_button_andern',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 20,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_58afd5fdfa4fe',
				'label' => 'Bewerben-Button Text',
				'name' => 'bewerben-button_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58afd651fa4ff',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => 40,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_58afd67efa500',
				'label' => 'Bewerben-Button Link',
				'name' => 'bewerben-button_link',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58afd651fa4ff',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => 40,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5955da27d1692',
				'label' => 'Conversion-Page für Stellenagebot als E-Mail',
				'name' => 'cp_stellenagebot_als_mail',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'conversionpages',
				),
				'taxonomy' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_59509f37790df',
				'label' => 'Ansprechpartner',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_583edd5c78d80',
				'label' => 'Vorname des Ansprechpartners',
				'name' => 'vorname_des_ansprechpartners',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Timm',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_5846aecfa0ce3',
				'label' => 'Nachname des Ansprechpartners',
				'name' => 'nachname_des_ansprechpartners',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Funke',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_583edd8678d81',
				'label' => 'Position des Ansprechpartners',
				'name' => 'position_des_ansprechpartners',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Personalleiter',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_583edd9478d82',
				'label' => 'E-Mail des Ansprechpartners',
				'name' => 'e-mail_des_ansprechpartners',
				'type' => 'email',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 't.funke@mindsquare.de',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_58458d9e1c37d',
				'label' => 'E-Mail der Bewerbung',
				'name' => 'e-mail_der_bewerbung',
				'type' => 'email',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'bewerbung@mindsquare.de',
				'placeholder' => 'E-Mail für die Bewerbung',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_583edda778d83',
				'label' => 'Telefonnummer des Ansprechpartner',
				'name' => 'telefonnummer_des_ansprechpartner',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '0521 9345 939-94',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_583eddbd78d84',
				'label' => 'Bild des Ansprechpartners',
				'name' => 'bild_des_ansprechpartners',
				'type' => 'image',
				'instructions' => 'Das Bild sollte eine minimale Größe von 90x90px haben',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5a254de8bd2bf',
				'label' => 'Bild des Ansprechpartners für die Fachbereichsseiten',
				'name' => 'fb_bild_des_ansprechpartners',
				'type' => 'image',
				'instructions' => 'Dieses Bild wird bei den Stellenanzeigen der Fachbereichsseiten angezeigt.
	Das Bild sollte eine minimale Größe von 66x66px haben.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_59509f49790e0',
				'label' => 'Hintergrund',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_583fcf8365b35',
				'label' => 'Hintergrund Video Webm',
				'name' => 'hintergrund_video_webm',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'webm',
			),
			array(
				'key' => 'field_583fcfc165b36',
				'label' => 'Hintergrund Video MP4',
				'name' => 'hintergrund_video_mp4',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'mp4',
			),
			array(
				'key' => 'field_583fcfdc65b38',
				'label' => 'Hintergrund Video MOV',
				'name' => 'hintergrund_video_mov',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'mov',
			),
			array(
				'key' => 'field_5846d6c0de4f2',
				'label' => 'Hintergrund Bild Fallback',
				'name' => 'hintergrund_bild_fallback',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5955e70357421',
				'label' => 'Einsteigsseite',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5955e72357422',
				'label' => 'Anzahl der Einträge pro Seite',
				'name' => 'employment_notice-einsteigsseite-anzahl',
				'type' => 'number',
				'instructions' => 'Verändert die Anzahl der Suchergebnisse pro Seite. Wenn die Anzahl auf (-1) gesetzt wird, werden alle Ergebnisse angezeigt. Wenn die Anzahl auf (0) gesetzt wird, wird der Standardwert von 10 Ergebnissen pro Seite verwendet.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => -1,
				'max' => '',
				'step' => 1,
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_5955e77957423',
				'label' => 'Position der Kontaktanzeige',
				'name' => 'employment_notice-einsteigsseite-position',
				'type' => 'number',
				'instructions' => 'In den Größen (xs, sm) wird die Stellenanzeige zwischen den Suchergebnissen angezeigt.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => 1,
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_5bec2ddbeb11a',
				'label' => 'Logos',
				'name' => 'employment_notice_logos',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5bec2e56eb11b',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Logo hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_5bec2e56eb11b',
						'label' => 'Bild',
						'name' => 'bild',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'referenten-thumb',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			array(
				'key' => 'field_5bec3d0743a4e',
				'label' => 'Logo auf der Einzelseite',
				'name' => 'logo_auf_der_einzelseite',
				'type' => 'image',
				'instructions' => 'Dieses Logo wird unterhalb von "Wir bieten dir" ausgespielt.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'referenten-thumb',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5bed89ed708d6',
				'label' => 'Navigation',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5bed8a02708d7',
				'label' => 'Seiten mit Karriere-Navigation',
				'name' => 'seiten_mit_karriere-navigation',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => array(
				),
				'allow_null' => 1,
				'multiple' => 1,
				'return_format' => 'id',
				'ui' => 1,
			),
			array(
				'key' => 'field_5bfd3b6c08fdd',
				'label' => 'Eingabe im Terminal',
				'name' => 'terminal_text',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5bfd3b8c08fde',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5bfd3b8c08fde',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5bfd493d2c8ee',
				'label' => 'Vor der Eingabe im Terminal',
				'name' => 'terminal_before',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_5bfd619508479',
				'label' => 'Nach der Eingabe im Terminal',
				'name' => 'terminal_after',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_5cb6c23b7ad0e',
				'label' => 'Kategorien mit Karriere-Navigation',
				'name' => 'kategorien_mit_karriere-navigation',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'category',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-stellenanzeigen',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	endif;