<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_577636e3bd5ef',
		'title' => 'Seminare',
		'fields' => array(
			array(
				'key' => 'field_577cb58598ef1',
				'label' => 'kurzer Einleitungstext',
				'name' => 'kurzer_einleitungstext',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 100,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'new_lines' => '',
				'maxlength' => '',
				'placeholder' => '',
				'readonly' => 0,
				'disabled' => 0,
				'rows' => '',
			),
			array(
				'key' => 'field_5d80a18af0938',
				'label' => 'Ihr Ziel',
				'name' => 'ihr_ziel',
				'type' => 'wysiwyg',
				'instructions' => 'Wird im Schulungskatalog ausgespielt',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_57b5bb4be50f5',
				'label' => 'Schulungsinhalte',
				'name' => 'schwerpunkte',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_59098c63ee931',
				'label' => 'Voraussetzungen',
				'name' => 'voraussetzungen',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_59098cafee932',
				'label' => 'Zielgruppe',
				'name' => 'zielgruppe',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_57764143da503',
				'label' => 'Video',
				'name' => 'video',
				'type' => 'oembed',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 60,
					'class' => '',
					'id' => '',
				),
				'width' => '',
				'height' => '',
			),
			array(
				'key' => 'field_5784a8ea2ccad',
				'label' => 'Bild anstatt Video',
				'name' => 'bild_anstatt_video',
				'type' => 'image',
				'instructions' => 'Wenn kein Wistia-Video zum Seminar vorhanden ist, muss ein Bild gewählt werden. Das Bild muss die Maße 555 x 312px haben.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 100,
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 555,
				'min_height' => 312,
				'min_size' => '',
				'max_width' => 555,
				'max_height' => 312,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_577e1ee4930d5',
				'label' => 'Referent',
				'name' => 'referent',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 100,
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'advisor',
				),
				'taxonomy' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_5d80a4415bdcd',
				'label' => 'Abschlusszertifikat',
				'name' => 'certificate',
				'type' => 'image',
				'instructions' => 'Wird im Schulungskatalog ausgespielt',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => 472,
				'max_height' => 295,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_578745bc4b907',
				'label' => 'Detailbeschreibung',
				'name' => 'detailbeschreibung',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_57bc35c508723',
				'label' => 'Seminarthemen und Agenda im Überblick',
				'name' => 'seminarthemen_und_agenda_im_uberblick',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_59257b7bac8cc',
				'label' => 'Art',
				'name' => 'seminar_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Seminar' => 'Seminar',
					'E-Learning' => 'E-Learning',
				),
				'default_value' => array(
					0 => 'Seminar',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_592580dd07731',
				'label' => 'Externer Link',
				'name' => 'e_learning_link',
				'type' => 'url',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_59257b7bac8cc',
							'operator' => '==',
							'value' => 'E-Learning',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_59257cead08f2',
				'label' => 'Dauer',
				'name' => 'e_learning_dauer',
				'type' => 'number',
				'instructions' => '6,5 Stunden',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_59257b7bac8cc',
							'operator' => '==',
							'value' => 'E-Learning',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Stunden',
				'min' => 0,
				'max' => '',
				'step' => '0.5',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_59257d2ad08f3',
				'label' => 'Preis',
				'name' => 'e_learning_preis',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_59257b7bac8cc',
							'operator' => '==',
							'value' => 'E-Learning',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Euro zzgl. USt.',
				'min' => 0,
				'max' => '',
				'step' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_592521f03eb06',
				'label' => 'Anzahl Seminartage',
				'name' => 'anzahl_seminartage',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_59257b7bac8cc',
							'operator' => '==',
							'value' => 'Seminar',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Tag(e)',
				'min' => 1,
				'max' => '',
				'step' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_592522563eb07',
				'label' => 'Uhrzeit von - bis',
				'name' => 'uhrzeit_von_-_bis',
				'type' => 'text',
				'instructions' => 'Beispiel: 09:00-17:00',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_59257b7bac8cc',
							'operator' => '==',
							'value' => 'Seminar',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_58ef836af0660',
				'label' => 'Seminare',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_59257b7bac8cc',
							'operator' => '==',
							'value' => 'Seminar',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_57bc563666717',
				'label' => 'Seminarpreis',
				'name' => 'preis',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Euro zzgl. USt.',
				'min' => 0,
				'max' => '',
				'step' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_577636f9d345f',
				'label' => 'Seminartermine',
				'name' => 'seminartermine',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 100,
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_57763898d3463',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Termin hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_57763719d3460',
						'label' => 'max. Anzahl Seminarteilnehmer',
						'name' => 'max_anzahl_seminarteilnehmer',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'default_value' => 10,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_577637b5d3461',
						'label' => 'Wenige Plätze bis',
						'name' => 'wenige_platze_bis',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'default_value' => 4,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_57763832d3462',
						'label' => 'Anzahl freie Plätze',
						'name' => 'anzahl_freie_platze',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_57763898d3463',
						'label' => 'Von Datum',
						'name' => 'von_datum',
						'type' => 'date_picker',
						'instructions' => 'Beispiel: 08.10.2016',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'display_format' => 'd.m.Y',
						'return_format' => 'd.m.Y',
						'first_day' => 1,
					),
				),
			),
			array(
				'key' => 'field_57763bfe248ba',
				'label' => 'Teilnehmerstimmen',
				'name' => 'teilnehmerstimmen',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 100,
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_57763d92248bc',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Teilnehmerstimme hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_57763d50248bb',
						'label' => 'Personenbild',
						'name' => 'personenbild',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 10,
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_57763d92248bc',
						'label' => 'Vor- und Nachname',
						'name' => 'vor-_und_nachname',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 10,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_57763db9248bd',
						'label' => 'Titel der Teilnehmerstimme',
						'name' => 'titel_der_teilnehmerstimme',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 10,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_57763deb248be',
						'label' => 'Text-Bewertung',
						'name' => 'text-bewertung',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 40,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_57763e1c248bf',
						'label' => 'Unternehmen',
						'name' => 'unternehmen',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 10,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_57763e35248c0',
						'label' => 'Position im Unternehmen',
						'name' => 'position_im_unternehmen',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 10,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_57763e7e248c1',
						'label' => 'Bewertung Referent',
						'name' => 'bewertung_referent',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 5,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 1,
						'max' => 5,
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_57763ea8248c3',
						'label' => 'Bewertung Inhalt',
						'name' => 'bewertung_inhalt',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 5,
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 1,
						'max' => 5,
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array(
						'key' => 'field_577641139280a',
						'label' => 'Unternehmenslogo',
						'name' => 'unternehmenslogo',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 10,
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5784a9b02ccaf',
						'label' => 'Teilnehmerstimme Video',
						'name' => 'teilnehmerstimme_video',
						'type' => 'oembed',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 100,
							'class' => '',
							'id' => '',
						),
						'width' => '',
						'height' => '',
					),
				),
			),
			array(
				'key' => 'field_58ef82e6f065f',
				'label' => 'Inhouse-Seminare',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_59257b7bac8cc',
							'operator' => '==',
							'value' => 'Seminar',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58ef7fcf13f62',
				'label' => 'Inhouse-Preis',
				'name' => 'inhouse_preis',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Euro zzgl. USt.',
				'min' => 0,
				'max' => '',
				'step' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array(
				'key' => 'field_5947ca75116bc',
				'label' => 'Seminar-Slider',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 1,
			),
			array(
				'key' => 'field_5947cd40116bd',
				'label' => 'Seminare',
				'name' => 'seminar_slider',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'seminare',
				),
				'taxonomy' => array(
				),
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'object',
				'ui' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'seminare',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'slug',
			5 => 'author',
			6 => 'format',
			7 => 'page_attributes',
			8 => 'tags',
			9 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));

endif;
